# "PRODUCTION bluemonkeymakes-boilerplate server v1.0 docker compose
services:
  nestjs-bluemonkeymakes-boilerplate-staging: # this container name is overrun by config
    image: $DOCKER_IMAGE_NAME
    container_name: $DOCKER_CONTAINER_NAME
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.staging
    ports:
      - ${PORT}:${PORT}
    environment:
      - ENV=staging
      - NODE_ENV=staging
      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}
      - CLIENT_API_KEY=${CLIENT_API_KEY}
      - CLIENT_URL=${CLIENT_URL}
      - HOSTNAME=${HOSTNAME}
      - BASE_URL=${BASE_URL}
      - PORT=${PORT}
      - SERVER_SECRET=${SERVER_SECRET}
      - API_VERSION=${API_VERSION}
    depends_on:
      - db-staging

    
  db-staging:
    image: postgres:13.3
    container_name: bluemonkeymakes-boilerplate-postgres-staging
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5632:5432"
    volumes:
      - bluemonkeymakes-boilerplate-db:/var/lib/postgresql/data
    networks:
      - bluemonkeymakes-boilerplate-network
    restart: unless-stopped

volumes:
  bluemonkeymakes-boilerplate-db:

networks:
  bluemonkeymakes-boilerplate-network:
    driver: bridge
 
##
### build
## docker compose --env-file ./env/.env.production --file ./docker/docker-compose.production.yaml  build --no-cache
##
### build and server
## docker compose --env-file ./env/.env.production --file ./docker/docker-compose.production.yaml  up --build -d
##
### fresh build and server and image no deps
## docker compose --env-file ./env/.env.production --file ./docker/docker-compose.production.yaml  up --build --force-recreate --no-deps
### up and watch
## docker compose --env-file ./env/.env.production --file ./docker/docker-compose.production.yaml  up --watch
